apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: landing-html
    files:
      - html/index.html
      - html/robots.txt
      - html/sitemap.xml
    options:
      disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
