---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cv-gate-secret
  namespace: matflixlab
spec:
  encryptedData:
    RESEND_API_KEY: AgB2h488Qvf7kiw5QAs2FjlV8vbhVPg3iIjwWaDGbCQG6VNTLLAI9o4tTUvkEOxU30+v5rrTie7yDWPpO4w8Aj9ttTHCy9VLUFBukv9qey9rqbJ3y0OBKjkSNZk8jR5+tC6rk5W3kBqWFp8Lj/kPoibMRZC3UM9FY+LoFNSiR65fYD4+RjChH9zp/N3qmYntnAV1AIANHmVjebYyo2G08PkuQH9JzV3pf28Hb9jJc/J0pnoyGi68YfD2/SZavz8ROYub2UxemntMvBhN2XZWSM9ejzlH02+hbDwrJl0qX4BlzVc86xyMmSI4urZ53SRC6HEJ8vLrG603Dsz5lkGcStDe3FdoU0C3eFflWyMAtjRTHq7wH9Rl6AJC/xJcoh0w9d43QsNLgoRk+ILu1ddFuJxuIVs/7QSs6L7iiPmLACeWuHFqEE7s+3jTX1kvEc/EhSqEV9676tDfDM7kWjYwWy4tQvF1MSsHnJkTCqtjqcuv7RWHWWydNPiFU1T9eHot0XIFyqBe4300U0zqyMss/xAUwSQFfVG9trRfiqzyGbJ90pdbO/FqhE02o3q6A2cFWcROh+80un7LGQ2ofjqxLnOHVrtCl87ENIxEdP3gKMuuNfZJt2DdDuWPMRYN4xUj8UwQUI5nfnKGbIMAKYgI1PsFUJzZ4ieFALCH5D4qP32FU++BO8hAnnaTlxNhg64mwcJ3qC37SXXR0TBt6oE7k/UUACIwNubyLa1buRtYJ1wMPOdFZSY=
  template:
    metadata:
      name: cv-gate-secret
      namespace: matflixlab
    type: Opaque
