apiVersion: v1
kind: Secret
metadata:
  name: matflixlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:matflixlab/matflixlab.git
  sshPrivateKey: |
    REPLACE_WITH_PRIVATE_KEY
