apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - infrastructure/namespaces/namespaces.yaml
  - infrastructure/registry/deployment.yaml
  - infrastructure/registry/service.yaml
  # Apps
  - apps/landing
  - apps/speakstats
  - apps/jellyfin
  - apps/monitoring
