apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-tech-news-data-pvc
  namespace: matflixlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
