---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-tech-news-secret
  namespace: matflixlab
spec:
  encryptedData:
    OPENAI_API_KEY: AgAyVkUDfIIhqNnKb0E1CEQS8fUWgrzde9nmwMUbOTHdsF4hudGUwFojN00FM9i3Xy5Yymi/wNabAHnt/4kOUwpg3A6rPZpITT08uojR+V8/A0ZQkJR0Jao1qLpWQvBRJOaxl9X1Cvbolqz+bsSuKYaAkHUIXd2tB+vTZPTXn7FEviWA4PSjyJ8W5YF8tP4kM6/mqMsQb2a+7Zn20yWxLvBOu3elQQs7roiX7ZOWJ83kmkMh6QMudedLy1K0ikKoy0whbFpFokikFLQZ4rbgH2WUP88/LqUJc2aGEeVjw1/nBHbtmJXz6Qe2JmQtdS3/Bzp9QTczhBkrS0XCF/vNMdsIwUImVsPUXQZYwH57ZSBLwEUzE1rg7DWaiDgM8KrgWkG0gCo8MXphd/ME2rHX9MANQ4cGUqpHz2FfvHhJLuWReLRNKlSuT+imK7L+NLidtEtJz9/Q4rRAsI9rIrlu8HZ9GHU8z1PCG0mbbFvcTcziFrxVhu67XEBeZaN1vO7xlxWJC+nJF68FWtqdKDw6ABHUr6KinysydZTfQhxw5FMHG5xHMtWFmViBW3PmiNU26Kj9z0nx6VKRPuD+XdkcxrYLpcJKl38ob3GGkvzCb8uTTIXMpVojpPK58Y8uDJlT1fFOCFLUK194JOTY+sEfFIm8vkKX7zbk3ZOmDzlZK5yxFIgCASKNiQ/JTaNGewaq+hxYcwKVA6A6Li6C43Nm1/9TIGcF5BGxujuGY5yIcjDaKPhF8m4DX7uLKoyIM+bzYI2yBNHsrd4CBQB8M0lKPQ+KPkN9161bB7mAnY1jCpGYLpSb2h11df73F7f7qC2O5XWaJ7BFp4xWR8urXPsYBWZZaIC59EGDonQPUtwd/UPY4MwdStTPlwraP3Me/qkkrdyhUzfiKwrjHwiQJ/QhD3QBvrDw2w==
  template:
    metadata:
      name: dev-tech-news-secret
      namespace: matflixlab
