apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speakstats-uploads-pvc
  namespace: matflixlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
