apiVersion: v1
kind: Namespace
metadata:
  name: matflixlab
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    app.kubernetes.io/managed-by: kustomize
