---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAf5/GiWb93hQfNg8bkgqFNQSlWNeTBbF1yANojyvNQq1/box8FuhJDt+si8ZpahMtrxJRH6pYwSWVQVl01Qn2vRTgx66hD9R9vL8g6wIvsUqhI0ObD8zJD2ogD8NCIoRDH+y1UYzt6J64RUdHIXT5OmmLgcIyTuPl2G32uSqep16jgC1SmZLDZh4rXkySqbvwKYLrjKA2QkT89In8J0/rUoF+5jmLBDCgi7VEahHikAPyqk7plI5H9rX/ZIG6UTTrmrYPL5bNkXzt5MWTpiElYS1Z7iTJgfsob9oG3VPnGFX5WlgaA9LeCGcxsmE0DOOVWO9Jr8+VnNnBTLoGgvc1Dcnzo8vs/RZkzw//TwXl+KarqFagWN7poLgAVbfE7zoFlhyz2y6RqgXfhyPmd/pX0lM1hvUl/yEuq4CeV22RVHerBKEXa8SCXqsI1vgMMJ/yazqg+u0e5uTHfklviDeN9rM0Ca4iMv+607HnbhEm9NcTwXY2jaQoocKp7ahaZHdMTT1Xs6erjzU4IQJLCdGVb5ejZSTLaaSIxx7IZS4QHT7aep9U5a4RPe8nwfPTHVeBjAt4Y72Q3QEn3Wo6I7GUfXYzK23Z637Pt6vbyI+LHAGPNnRDD2SuvfZR8LIHIQliqqbtdqUqg0FCMfE5CdDEx3l5o3eSsis3Zivd7gPpBhEf1V3kuDXRzh4HPQXgmVW1oKKm9yz5Hygn1EQ0W/8zeLTSG+ZaKAWTKm9FsbxCySp+VpwbOVzt9bMGwBoTMVvpivC8YefXfNG58M76wG6pd/bGfe+o=
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
